### ISSUE TITLE
What exactly can you control with this SDK. (Use case presented inside)

### ISSUE THREAD

**Issue by dhodgin** [CorsairOfficial/cue-sdk-node#12]
The documentation could use a little more introduction and broad explanation on what you can do with this library and what devices are supported.

I am currently looking for both a RGB mouse mat and a RGB keyboard that can be programmatically controlled with a node sdk to change the colors based on data coming in for stock market prices and portfolio data.

I want to change the colors of the RGB mat lighting to reflect conditions on prices in realtime and update specific keys on the keyboard with colors to reflect certain notifications based on prices and my portfolio data.

I am looking to integrate it with Interactive Brokers which I can already do with node.js I just need a solution on the mouse mat and keyboard side for the color changes.

I am looking at corsair, logitech, and razr for solutions via SDKs for node.

This one looks promising but the readme doesn't say what hardware is supported or if something like this might be possible.

I like the Corsair MM700 RGB mat and it says it works with iCUE so I'm wondering if this SDK supports it and can modify the rgb on demand programmatically.

**Comment by intrueder** [comment]
I agree, the documentation should be improved in this repo.
Although, this repo is just a wrapper around the [native library](https://github.com/CorsairOfficial/cue-sdk), so you can check the docs there https://corsairofficial.github.io/cue-sdk/#supported-devices

**Comment by intrueder** [comment]
I just realized that the Corsair MM700 RGB is missing from the list of supported devices, but CUESDK does support it.

**Comment by intrueder** [comment]
Updated README.md with the "List of supported devices" link
