### ISSUE TITLE
Help to access color values

### ISSUE THREAD

**Issue by TheTheoM** [CorsairOfficial/cue-sdk-node#20]
Hey, How Do I access the color values of an LED? 

It is doable in the python version.

**Comment by intrueder** [comment]
@TheTheoM , you need either [CorsairGetLedsColors ](https://github.com/CorsairOfficial/cue-sdk-node/blob/master/api-reference.md#corsairgetledscolorscolors) or [CorsairGetLedsColorsByDeviceIndex](https://github.com/CorsairOfficial/cue-sdk-node/blob/master/api-reference.md#corsairgetledscolorsbydeviceindexdeviceindex-colors) function. As a `colors` argument, pass an array of LED color objects, you can construct it manually or transform a result from `CorsairGetLedPositions` function:

```js
const leds = sdk.CorsairGetLedPositions().map(led => ({ ledId: led.ledId, r: 0, g: 0, b: 0 }));
sdk.CorsairGetLedsColors(leds);
console.log(leds);
```
