### ISSUE TITLE
Latest iCue update breaks this integration

### ISSUE THREAD

**Issue by spdermn02** [CorsairOfficial/cue-sdk-node#21]
iCue Software: v4.24.193

cue-sdk-node: v3.1.0

As of the latest iCue software update, the SubscribeToEvents is no longer triggering for macrokeyup/macrokeydown from my K55 RGB keyboard.  This issue affects a plugin I've built for Touch Portal, but also seems to affect the Stream Deck app as well being able to utilize the Macro keys from the keyboard.

Events trigger for device disconnected/device connected, but nothing else.

**Comment by spdermn02** [comment]
updated to v4.25.155 of iCue and G keys still do not work in either the sdk nor through Streamdeck software.

**Comment by intrueder** [comment]
Hi @spdermn02, can you share a list of devices displayed on the iCUE home tab? Specifically, I'm interested in a number of keyboards connected to your PC.

Linking a similar issue: https://github.com/CorsairOfficial/cue-sdk-python/issues/15

**Comment by spdermn02** [comment]
I only have one keyboard the K55 RGB. It seems like it's an iCue software issue vs the SDK interface (I presume) since that is what updated in this scenario that caused it to break. 

Running the code while developing connects but returns 0 keyboards connected even though I know for SURE it's connected as iCue reports it and the RGB changes to my configured profile. Firmware on keyboard is up to date according to iCue. Updated to the latest version of iCue and of course still an issue. And also using the Elgato Stream Deck integration to assign G keys, doesn't do anything when I push them either.

**Comment by spdermn02** [comment]
went back and installed the "legacy" version of iCue and the macrokeys are back. Maybe my keyboard is no longer being supported properly in the new versions of icue. I'll test and update later but for now I get my G key access back.
