### ISSUE TITLE
__dirname reference to node-gyp-build prevents packaging as executable

### ISSUE THREAD

**Issue by 24bitIO** [CorsairOfficial/cue-sdk-node#9]
In trying to package my node app as an executable using 'pkg' I receive this error when launching the .exe:

```
Error: No native build was found for platform=win32 arch=x64 runtime=node abi=83 uv=1 libc=glibc node=14.4.0
    loaded from: D:\snapshot\order_flash\node_modules\cue-sdk
```

It's described well here: https://github.com/parcel-bundler/parcel/issues/5090

The problem arises in line 1 of index.js:
`const binding = require('node-gyp-build')(__dirname)`

To recreate: simply require the cue-sdk module, and run pkg.

**Comment by 24bitIO** [comment]
Maybe this isn't the most correct fix, but I got around it by changing line 1 to:
`const binding = require('node-gyp-build')('node_modules/cue-sdk')`

**Comment by intrueder** [comment]
This is more like an issue with `pkg`: https://github.com/vercel/pkg#native-addons

> Native addons (.node files) use is supported, but packaging .node files inside the executable is not resolved yet. You have to deploy native addons used by your project to the same directory as the executable.

Try to copy `node_modules/cue-sdk/prebuilds` folder to the same folder as the executable.
